courses/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.course_list),
    path('<int:course_pk>/<int:step_pk>', views.step_detail),
    path('<int:pk>/', views.course_detail),
]

learning_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path('courses/', include('courses.urls')),
    path('admin/', admin.site.urls),
    path('', views.hello_world)
]

urlpatterns += staticfiles_urlpatterns()

courses/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    
    def __str__(self):
        return self.title


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(
                            'Course',
                            on_delete=models.CASCADE,
                            )
    
    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.title

courses/views.py
from django.shortcuts import get_object_or_404, render

from . models import Course, Step

# Create your views here.
def course_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})

def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})

def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})

learning_site/views.py
from django.shortcuts import render

def hello_world(request):
    return render(request, 'home.html')

courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
<article>
    <h2>{{ course.title }}</h2>
    {{ course.description }}

    <section>
        {% for step in course.step_set.all %}
        <h3>{{ step.title }}</h3>
        {{ step.description }}
        {% endfor %}
    </section>
</article>

{% endblock %}

courses/templates/courses/course_list.html
{% for course in courses %}
<h2>{{ course.title }}</h2>
{{ course.description }}
{% endfor %}

courses/templates/courses/step_detail.html
{% extends "layout.html" %}

{% block title %}{{ step.title }}-{{ step.course.title }}{% endblock %}

{% block content %}
<article>
    <h2>{{ step.course.title }}</h2>
    <h3>{{ step.title }}</h3>
    {{ step.content|linebreaks }}
</article>
{% endblock %}

templates/home.html
{% extends "layout.html" %}

{% block title %}Well Hello and Welcome! {% endblock %}

{% block content %}
<h1>Welcome!</h1>
{% endblock %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
</head>
    <body>
        <div class="site-container">
                {% block content %}{% endblock %}
        </div>
    </body>
</html>